ClimateMind/frontend-native-app

screens/tabs/ConversationsScreen/ConversationCard.tsx

https://github.com/orgs/ClimateMind/projects/3?pane=issue&itemId=29214075

[CLOSES #34] ConversationCard: Change the header text depending on the state

---

components/RadarChart.tsx
screens/drawer/PersonalValuesScreen.tsx
screens/stack/PersonalValuesScreenNewUser/PersonalValuesScreenNewUser.tsx

Link to ticket in Project:
https://github.com/orgs/ClimateMind/projects/3/views/1?pane=issue&itemId=30353938

[CLOSES #49] Implement Personal Values Screen

---

App.tsx
hooks/useApiClient.tsx
package-lock.json
package.json
store/authSlice.ts

https://github.com/orgs/ClimateMind/projects/3?pane=issue&itemId=29245390

[CLOSES #56] Implement token refresh

---

screens/tabs/ConversationsScreen/ConversationsDrawer.tsx

Had to add padding to top and bottom of View container. The issue is that the arrow at the top was cut off on my phone and the bottom was also cut off. This may not be the same on Android. I originally intended to add margin to the Flat list but though it better in the main view.

[CLOSES #66] Fix cutoff Conversation Drawer

---

.env
.gitignore
components/ToastMessages.tsx
screens/stack/LoginScreen/LoginScreen.tsx
screens/stack/LoginScreen/PasswordResetModal.tsx
screens/tabs/ConversationsScreen/ConversationsScreen.tsx
screens/tabs/ConversationsScreen/CopyLinkModal.tsx
store/authSlice.ts

Have added some comments about the logic of the clipboard functions. I had to make the copy button a dummy copy button because the actual setting and getting of the url link has to be done upfront and before pressing the copy button so the text can be displayed on the modal.

[CLOSES #63] Enhance Copy Link Experience | Create Modal and optionally a Toast Message

---

.env
hooks/useApiClient.tsx

I don't know if the refresh endpoint on the backend works properly as it seems difficult to implement that properly.
For now, the only solution is to just logout the user and give him a message that his session has expired.
It is not a great solution for the user, but for now the only thing that works.

Logout User if access token Expires

---

components/SimpleWhiteButton.tsx
navigation/DrawerNavigation/CustomDrawerContent.tsx
navigation/DrawerNavigation/SocialImagesGrid.tsx

…<img width="1436" alt="iosandroid" src="https://github.com/ClimateMind/frontend-native-app/assets/39728053/d46dbdf7-5ef1-4664-89e5-7781284267b6">

[CLOSES #118] Improve Drawer Visibility

---

screens/tabs/ConversationsIntroScreen/ConversationsIntroScreen.tsx

#147 - Added extra padding to button

---

NavigationRoot.tsx
components/Cards/Card.tsx

Added shadows for IOS and kept the elevation for Android. See images

[CLOSES #148] Add Shadows to the Card Component

---

screens/tabs/ConversationsScreen/ConversationCard.tsx

Added modal. Please can you test on Android? All looks ok on ios.

[CLOSES #153] Add Modal to Copy Link Button in Conversation Card

---

assets/colors.ts
hooks/useApiClient.tsx
screens/onboarding/OnBoardingScreens.tsx
screens/tabs/ClimateFeedScreen/ClimateFeedScreen.tsx
screens/tabs/ConversationsIntroScreen/ConversationsIntroScreen.tsx
screens/tabs/ConversationsScreen/ConversationsScreen.tsx
screens/tabs/ConversationsScreen/SeeHowYouAlignModal.tsx
screens/tabs/ConversationsScreen/ViewSelectedTopicsModal.tsx
screens/tabs/MythsFeedScreen/MythsFeedScreen.tsx
screens/tabs/ProfileScreen/ProfileScreen.tsx
screens/tabs/SolutionsFeedScreen/SolutionsFeedScreen.tsx

https://github.com/orgs/ClimateMind/projects/3?pane=issue&itemId=34563417

[CLOSES #158] Fix Bright Background Color

---

hooks/useApiClient.tsx
screens/stack/LoginScreen/LoginScreen.tsx

See project:
https://github.com/orgs/ClimateMind/projects/3/views/1?pane=issue&itemId=35219888
To properly test it you must update the climatemind-backend, because a new functionality has been added there to skip the captcha. So just pull the most recent develop branch. (Or alternatively you just test it with the qr code below)

[CLOSES #162] Only show Recaptcha after failed Login Attempts

---

hooks/useApiClient.tsx
store/authSlice.ts

See project:
https://github.com/orgs/ClimateMind/projects/3/views/1?pane=issue&itemId=35251284
We can talk about it in our next meeting to understand / test it.

[CLOSES #164] Implement the Refresh Mechanism Properly

---

screens/UserAAuthorizedScreens/ConversationsScreen/ConversationCard.tsx
screens/UserAAuthorizedScreens/ConversationsScreen/ConversationRating.tsx
screens/UserAAuthorizedScreens/ConversationsScreen/NotifyIcon.tsx

Would you be able to test this. I think this simple solution works ok.  Not sure if you want me to move the NotificationIcon.tsx to components but I put it in the ConversationsScreen folder. Thanks

[CLOSES #172] Show Notify Icon for Updates in Conversation

---

components/SimpleWhiteTextButton.tsx
screens/UserAAuthorizedScreens/ConversationsIntroScreen/ConversationsIntroScreen.tsx

Had to take out the height property and add  flexShrink:1,  flexWrap: 'wrap' and that sorted it. Can you test on android please :-)

took out height and added flex

---

navigation/UserAAuthorizedTabsNavigation.tsx
screens/UserAUnauthorizedScreens/StartScreen/StartScreen.tsx

Had to change make it so the themecolor was don't he very top level eg ScrollView as this was showing white on Apple Ipad. I have also change the width of the profile user intials on the nav tab because they were not on the same line. Can you test in Android please.

fixed themecolor and added width to profile tab

---

components/BulletListItem.tsx
screens/UserAAuthorizedScreens/ConversationsIntroScreen/ConversationsIntroScreen.tsx
screens/UserAAuthorizedScreens/ConversationsScreen/ConversationCard.tsx

https://github.com/orgs/ClimateMind/projects/3/views/1?pane=issue&itemId=37217440

[CLOSES #202] Fix Misaligned Dots

---

src/screens/UserAAuthorizedScreens/ConversationsScreen/SeeHowYouAlignModal.tsx

A clear and concise description of what the PR accomplishes.
List the changes made in this PR.
- [x ] I have tested this code.

Added a new state for topSimilarvalue and type of number

---

src/shared/components/CmButton.tsx

Set isLoading to false as it was set to true which means the loader was just spinning
Set isLoading to false as it was set to true which means the loader was just spinning on every button

set isLoadin to false

---

src/features/conversations/components/ConversationCard.tsx
src/shared/components/CmIconButton.tsx

[CLOSES #478] create-another-trashcan-variation-for-the-cmicon-button-and-add-it-to-the-conversationcard
Added Foundation Icon variant to the CmIconButton
Added Foundation Icon variant to the CmIconButton and used it in ConversationCard to replace trash icon.

[CLOSES #478] Create another trashcan variation for the cmicon button and add it to the conversationcard

---

src/features/conversations/components/ConversationCard.tsx
src/features/conversations/components/ConversationsIntroCard.tsx

Added CmButton to replace pressable for moreless
Imported button for ConversationCard and ConversationCardIntro components.
Made some some styling modifications to match the original pressable.

495 add moreorless component to conversationscard

---

src/features/climate-feed/components/ClimateFeedCard.tsx
src/screens/UserAAuthorizedScreens/ClimateFeedScreen.tsx
src/shared/components/CmChip.tsx

Added a tooltip to the CmChip component. 
Chip label has been made into a pressable.
Added a fade-in and fade-out animation.
The tooltip takes text from an object and this has been added to a new CmTypography component. 

500 create a tooltip modal for all of the app tags on the home navigation tab

---

package-lock.json
package.json
src/features/climate-feed/components/ClimateFeedCard.tsx
src/shared/components/Cards/Card.tsx
src/shared/components/CmChip.tsx

title: [CLOSES #522] Turn the tooltip into a tooltip that needs to be manually closed on press 
Changed the logic so that to open the tooltip the user needs to press on the chip and to exit they need to press again.
All logic moved to ClimateFeedCard because I needed to use the map index and remove it from the chip for it to work.  I will convert this to its component soon after but at this point, it's just to get it into production.

[CLOSES #522] Turn tooltip into a tooltip that needs to be manually closed on press
